### ISSUE TITLE
I have got a problem

### ISSUE THREAD

**Issue by zef-nomer** [Dreamyplayer/DANG#1]
![image](https://user-images.githubusercontent.com/80211406/129946337-d93096e7-001a-4ab2-adcd-c4da7a6466ed.png)
help pls

**Comment by tzt345** [comment]
[Go Here :)](https://stackoverflow.com/questions/23632914/how-to-handle-etimedout-error)

**Comment by Dreamyplayer** [comment]
Just a Network issues fixed already
