### ISSUE TITLE
Wont work on Replit

### ISSUE THREAD

**Issue by Odin5569** [Dreamyplayer/DANG#23]
Made by ♔ Dяεαмү アlαүεя ♔ With ❤️

Need help? Join Our Discord 
https://discord.gg/CNAJfbs5dn

Proxies 
UP: 1
ALIVE: 1
DEAD: 0

[Launching] 200 checks, estimated time: 40m | Jun 9, 2024, 1:27 PM
[AUTO] grabbed 696 proxies.
[ETL] 3s Analyzed 2/200 [0] - continuing 198 codes
[ETL] 3s Analyzed 1/200 [0] - continuing 199 codes
[ETL] 4s Analyzed 3/200 [0] - continuing 197 codes
[ETL] 4s Analyzed 4/200 [0] - continuing 196 codes
 
 
 And i cant stop the Code and there is "Reconnecting" i think it is a virus!

**Comment by Dreamyplayer** [comment]
Replit employs a hot reloading mechanism, where it detects code modifications and restarts the application from the designated entry point (often "app.js" or similar), ensuring your server/app stays active during development. ~not virus~.
