### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by Shkeffy** [Dreamyplayer/DANG#5]
@Dreamyplayer Can you please tell me how to deploy it on Replit, please? Easier way to talk is Discord, my user is: Shkeffy#9999.

**Comment by Dreamyplayer** [comment]
Download/clone folder DANG & Upload to Replit 
add folders & files outise folder one by one (except node_modules and yarn.lock file) 
Click on Run it... to install packages
After installation of packages (you will get an error) open shell on right side
Type `node .` & enter it will start running

@Shkeffy

**Comment by Dreamyplayer** [comment]
i tried running in replit but it just starts and ends.
currently, i don't know the reason & fix...

**Comment by Shkeffy** [comment]
Okay, thank you!
