### ISSUE TITLE
Can't use in Debian/Windows

### ISSUE THREAD

**Issue by SapitoSucio** [Dreamyplayer/DANG#8]
I get the same problem in both platforms

![image](https://user-images.githubusercontent.com/7357354/195051379-81f0fd08-6c6e-44fb-aeec-961212a63874.png)

**Comment by Dreamyplayer** [comment]
Wait for code update, would be fixed in next update and I'll inform once done.

**Comment by Dreamyplayer** [comment]
Try now 
btw if you run `npm start` or `yarn start` it will auto update code Probably.
