### ISSUE TITLE
Prestart 

### ISSUE THREAD

**Issue by Ducci9129** [Dreamyplayer/DANG#9]
`@Ducci9129 ➜ /workspaces/NitroGen/DANG (main ✗) $ npm start

> dang@2.0.3 prestart
> git pull origin master && node -e 'setTimeout(()=>{},5000)' && node src/Generator

fatal: couldn't find remote ref master
@Ducci9129 ➜ /workspaces/NitroGen/DANG (main ✗) $ 
`

Im trying to run this in a codespace but continue to get this error. I have no idea what it means tho :/

**Comment by Dreamyplayer** [comment]
since there're new updates in project, you can remove 
`git pull origin master && node -e 'setTimeout(()=>{},5000)' &&` this line from `package.json` file would work fine in both ways.
